# Generated by Django 6.0.1 on 2026-01-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payments_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="method_payment",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")],
                help_text="Выберите способ оплаты",
                max_length=20,
                null=True,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
