# Generated by Django 6.0.1 on 2026-01-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payments_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="Укажите сумму оплаты", verbose_name="Сумма оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
