# Generated by Django 6.0.1 on 2026-01-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Скопируйте ссылку на видео",
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
